services:
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: alembic upgrade head
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/urlshortener
    depends_on:
      db:
        condition: service_healthy
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/urlshortener
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  db:
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
      
